name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build project
      run: |
        docker pull archlinux:base
        docker run -d -i -t --privileged -v `pwd`:/root/repo --name build archlinux:base
        docker exec -t build cat /etc/pacman.d/mirrorlist
        docker exec -t build cat /etc/pacman.conf
        docker exec -t build sed 's/^\#VerbosePkgLists/ParallelDownloads = 5/' -i /etc/pacman.conf
        docker exec -t build cat /etc/pacman.conf
        docker exec -t build pacman -Syy --noconfirm
        docker exec -t build pacman -Su --noconfirm
        docker exec -t build cat /etc/pacman.conf
        docker exec -t build pacman -S --needed --noconfirm base base-devel archiso gtk3 python-babel python-gobject python-psutil python-pylint python-pythondialog python-setuptools libxmu
